# Generated by Django 5.2.12 on 2026-03-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriphion',
            new_name='description',
        ),
    ]
